FOLIO-2097 avoid CommandList and HasCommand (#1139)
We have confirmed that `mousetrap`, a transitive dependency of 
`<CommandList>` and `<HasCommand>` has a memory leak (it appears
event listeners are not properly detached and recycled) and during CI this
causes OOM errors that lead to sporadic test failures. Obviously, we 
don't really want to get rid of key-bindings, but we really need to have 
passing unit tests, and reinstating these two wrapper components 
should be easy to revert. 

Unrelated, handle the spread-related syntax errors that showed up
after recent Babel updates in stripes-core, or possibly after updates
to ESLint, the lines that are changed here started triggering the error
```
Error: Uncaught TypeError: Invalid attempt to spread non-iterable instance
```
As noted at
https://stackoverflow.com/questions/53991403/typeerror-invalid-attempt-to-spread-non-iterable-instance,
you can't spread just anything:
```
function trySpread(object) {
  let array;
  try {
    array = [...object];
    console.log('No error', array);
  } catch(error) {
    console.log('error', error);
  }
}

// error
trySpread({});
trySpread({foo: 'bar'});
trySpread(4);

// no error
trySpread([]);
trySpread(['foobar']);
trySpread('foobar');
```
and though there's no boolean example in the "error" section there, that
appears to be the cause.

Refs FOLIO-2097, STCOM-636, UIU-1457, STCOR-381