handle spread-related syntax errors
Following the Babel updates in stripes-core, or possibly recent updates
to ESLint, the lines that are changed here started triggering the error
```
Error: Uncaught TypeError: Invalid attempt to spread non-iterable instance
```
As noted at
https://stackoverflow.com/questions/53991403/typeerror-invalid-attempt-to-spread-non-iterable-instance,
you can't spread just anything:
```
function trySpread(object) {
  let array;
  try {
    array = [...object];
    console.log('No error', array);
  } catch(error) {
    console.log('error', error);
  }
}

// error
trySpread({});
trySpread({foo: 'bar'});
trySpread(4);

// no error
trySpread([]);
trySpread(['foobar']);
trySpread('foobar');
```
and though there's no boolean example in the "error" section there, that
appears to be the cause.